CRM/API/urls.py
from django.urls import path
from API.views import *
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path('send-invit-api', InviteCreateAPIview.as_view()),
    path('takes-invit-serializer', InvitTakesAPIview.as_view()),
    path('api/token/', jwt_views.TokenObtainPairView.as_view()),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view()),
    path('issue-send-api/', IssueSendAPIview.as_view()),
    path('createuser', UserCreateAPIview.as_view()),
    path('project-add-api/', ProjectAddAPIview.as_view()),
    path('sprint-add-api/', SprintAddAPIview.as_view()),
    path('userstory-add-api/', UserstoryAddAPIview.as_view()),
    path('task-add-api/', TaskAddAPIview.as_view()),
    path('add-coment-for-sprint-api/', ComentAddSprintAPIview.as_view()),
    path('add-coment-for-userstory-api/', ComentAddUserstoryAPIview.as_view()),
    path('add-coment-for-task-api/', ComentAddTaskAPIview.as_view()),
    path('get-projects-for-user_admin/', ProjectsAdminListAPIview.as_view()),
    path('get-projects-for-user/', ProjectsListAPIview.as_view()),
    path('get-project-for-user/<int:pk>', ProjectListAPIview.as_view()),
    path('get-sprints-for-projects/<int:id>', SprintsListfoProjectAPIview.as_view()),
    path('get-userstory-for-sprint/<int:id>', UserstorysListSprintAPIview.as_view()),
    path('get-tasks-for-userstory/<int:id>', TaskListUserStoryAPIview.as_view()),
    path('get-issues-for-projects/<int:id>',IssuesListAPIview.as_view()),
    path('get-task-for-userstory/<int:pk>', TaskReturnAPIview.as_view()),
    path('update-issue-api/<int:pk>', IssueUpdateAPIview.as_view()),
    path('update-responsible-issue-api/<int:pk>', IssueChangeResponsibleAPIview.as_view()),
    path('update-status-issue-api/<int:pk>', IssueChangeStatusAPIview.as_view()),
    path('update-responsible-sprint-api/<int:pk>', SprintChandeResponsibleAPIview.as_view()),
    path('update-status-sprint-api/<int:pk>', SprintChangeStatusAPIview.as_view()),
    path('update-sprint-api/<int:pk>', SprintUpdateAPIview.as_view()),
    path('update-userstory-responsible-api/<int:pk>', UserStoryChangeResponsibleAPIview.as_view()),
    path('update-userstory-status-api/<int:pk>', UserStoryChangeStatusAPIview.as_view()),
    path('update-task-responsible-api/<int:pk>', TaskChangeResponsibleAPIview.as_view()),
    path('update-task-status-api/<int:pk>', TaskChangeStatusAPIview.as_view()),
]

CRM/CRM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('management/', include('management.urls')),
    path('api/', include('API.urls')),
]

CRM/management/urls.py
from django.urls import path
from .views import *
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path('search/', search_box),
    path('change-responsible-issue/', change_responsible_issue),
    path('create-coment-for-issue/', create_coment_for_issue),
    path('create-coment-for-task/', create_coment_for_task),
    path('create-coment-for-userstory/', create_coment_for_userstory),
    path('create-task-for-userstory/', create_task_for_userstory),
    path('create-userstory-for-sprint/', create_userstory_for_sprint),
    path('create-coment-for-sprint/', create_coment_for_sprint),
    path('form-add-issue/<int:id>', form_add_issue),
    path('form-add-sprint/<int:id>', form_add_sprint),
    path('create-issue/', create_issue),
    path('create-sprint/', create_sprint),
    path('create-project/', create_project),
    path('coment-for-task/<int:id>', coment_for_task),
    path('change-status-userstory/', change_status_userstory),
    path('userstory/<int:id>', user_story),
    path('change-responsible-userstory/', change_responsible_userstory),
    path('task/<int:id>', task),
    path('change-responsible-task/', change_responsible_task),
    path('user/<int:id>', user_info),
    path('sprint/<int:id>', sprint),
    path('change-status-task/', change_status_task),
    path('change-status-sprint/', change_status_sprint),
    path('change-responsible-sprint/', change_responsible_sprint),
    path('change-status-issue/', change_status_issue),
    path('change-status-issue-two/', change_status_issue_two),
    path('list-issues-two/<int:id>', list_issues_two),
    path('list-issues/<int:id>', list_issues),
    path('issue-info/<int:id>', issue_info),
    path('members-project/<int:id>', members_project),
    path('my-project/<int:id>', my_project),
    path('entrance', entrance),
    path('homepage', home_page),
    path('login', enter),
    path('logout', log_out),
    path('register', register),
    path('invite', invite),
    path('sendinvitation', send_invitation),
    path('emailconfirmation', emailconfirmation),
]

CRM/tasker/models/task.py
__all__=['Task', 'StatusTask']
from django.db import models
from django.contrib.auth.models import User
from .project import *
from .userstory import *

class Task(models.Model):
    name = models.CharField(max_length=250)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_task')
    responsible = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks', null=True, blank=True)
    status = models.ForeignKey('StatusTask', on_delete=models.CASCADE)
    user_story = models.ForeignKey(UserStory, on_delete=models.CASCADE, related_name='tasks', null=True, blank=True)
    description = models.TextField()
    time_completion = models.DateField(null=True)
    number = models.IntegerField()

    def __str__(self):
        return '{}, {}, {}, {}, {}, {}, {}, {}'.format(
            self.name,
            self.created_by,
            self.responsible,
            self.status,
            self.user_story,
            self.description,
            self.time_completion,
            self.number,
        )
    



class StatusTask(models.Model):
    alies = models.CharField(max_length=50, primary_key=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return '{}, {}'.format(
            self.alies,
            self.name,
        )

CRM/tasker/models/userstory.py
__all__=['UserStory', 'UserStoryStatus']
from django.db import models
from django.contrib.auth.models import User
from .project import *
from .sprint import *


class UserStory(models.Model):
    name = models.CharField(max_length=250,)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_userstorys')
    responsibles = models.ManyToManyField(User, related_name='performers_userstorys', blank=True)
    status = models.ForeignKey('UserStoryStatus', on_delete=models.CASCADE)
    description = models.TextField()
    sprint = models.ForeignKey(Sprint, on_delete=models.CASCADE, related_name='userstorys')
    date_create = models.DateField(auto_now_add=True)
    data_update = models.DateField(auto_now=True)
    data_closed = models.DateField(blank=True, null=True)
    number = models.IntegerField()

    def __str__(self):
        return '{}, {}, {}, {}, {}, {}, {}, {}, {}, {}'.format(
            self.name,
            self.created_by,
            self.responsibles,
            self.status,
            self.description,
            self.sprint,
            self.date_create,
            self.data_update,
            self.data_closed,
            self.number,
        )
    


class UserStoryStatus(models.Model):
    alies = models.CharField(max_length=50, primary_key=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return '{}, {}'.format(
            self.alies,
            self.name,
        )

CRM/management/views.py
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.utils.datastructures import MultiValueDictKeyError
import uuid
from .models.tokenemail import *
from .services import *
from .utilities import *
from django.dispatch import Signal
from tasker.models.project import *
from tasker.models.sprint import *
from tasker.models.issue import *
from tasker.models.userstory import *
from tasker.models.task import *
from tasker.models.coment import *
from django.contrib.auth.models import User

change_status_signal = Signal()
change_responsible_signal = Signal()


@is_auth
def coment_for_task(request, id):
    comentservis = ComentServis(request,id)
    data = comentservis.get_coment_for_task()
    context = {
        'data': data,
    }
    return render(request, 'comentfortask.html', context)


@is_auth
def create_coment_for_sprint(request):
    if request.user.has_perm('tasker.can_add_coment_for_sprint'):
        comentservis = ComentServis(request, id)
        data = comentservis.set_coment_for_sprint()
        return redirect('/management/sprint/{}'.format(data.sprint.id))
    else:
        return HttpResponse('Permission denied', status=403)


@is_auth
def create_coment_for_userstory(request):
    if request.user.has_perm('tasker.can_add_coment_for_userstory'):
        comentservis = ComentServis(request, id)
        data = comentservis.set_coment_for_userstory()
        return redirect('/management/userstory/{}'.format(data.userstories.id))
    else:
        return HttpResponse('Permission denied', status=403)


@is_auth
def create_coment_for_task(request):
    if request.user.has_perm('tasker.can_add_coment_for_task'):
        comentservis = ComentServis(request, id)
        data = comentservis.set_coment_for_task()
        return redirect('/management/task/{}'.format(data.task.id))
    else:
        return render(request, 'NotPermissionCreateComent.html')


@is_auth
def create_coment_for_issue(request):
    comentservis = ComentServis(request, request.POST['issue_id'])
    data = comentservis.set_coment_fot_issue()
    return redirect('/management/issue-info/{}'.format(data.issue.id))


@is_auth
@add_userstory_perm
def create_userstory_for_sprint(request):
    data = add_userstory_for_sprint(request.user, request.POST)
    if data == None:
        return render(request, 'NotCreate.html')
    elif data:
        return redirect('/management/sprint/{}'.format(data.sprint.id))



@is_auth
@change_userstory_perm
def user_story(request, id):
    comentservis = ComentServis(request, id)
    userstory = get_userstory(id=id)
    tasks = get_list_task(id=userstory['userstory'].id)
    coments = comentservis.get_coments_for_userstory()
    form_add_coment = CreateComentForm()
    form_add_task = CreateTaskForm()
    form_starus_userstoty = UserStoryStatusForm()
    form_responsible_form = ResponsibleUserstory()
    context = {
        'userstory': userstory,
        'tasks': tasks,
        'coments': coments,
        'form_add_coment': form_add_coment,
        'form_add_task': form_add_task,
        'form_starus_userstoty': form_starus_userstoty,
        'form_responsible_form': form_responsible_form,
    }
    return render(request, 'userstory.html', context)

@is_auth
@change_userstory_perm
def change_status_userstory(request):
    userstory = get_userstory(request.POST['userstory_id'])
    userstory_status = UserStoryStatusForm(request.POST, instance=userstory['userstory'])
    if userstory_status.is_valid():
        userstory_status.save()
        change_status_signal.send(sender=userstory['userstory'])
        return redirect('/management/userstory/{}'.format(userstory['userstory'].id))


@is_auth
@change_userstory_perm
def change_responsible_userstory(request):
    userstory = get_userstory(request.POST['userstory_id'])
    userstory_responsibls = ResponsibleUserstory(request.POST, instance=userstory['userstory'])
    if userstory_responsibls.is_valid():
        userstory_responsibls.save()
        change_responsible_signal.send(sender=userstory['userstory'])
        return redirect('/management/userstory/{}'.format(userstory['userstory'].id))



@is_auth
@create_task_perm
def create_task_for_userstory(request):
    data = add_task_for_userstory(request.user, request.POST)
    return redirect('/management/userstory/{}'.format(data.user_story.id))


@is_auth
@add_project_perm
def create_project(request):
    data = request.POST
    data = add_project(data)
    return redirect('/management/homepage')


@is_auth
def task(request, id):
    comentservis = ComentServis(request, id)
    task = get_task(id=id)
    coments = comentservis.get_coment_for_task()
    task_status = StatusTaskForm(request.POST, instance=task['task'])
    form_add_coment = CreateComentForm()
    form_responsible = ResponsibleTaskForm()
    context = {
        'task': task,
        'coments': coments,
        'form_add_coment': form_add_coment,
        'task_status': task_status,
        'form_responsible': form_responsible,
    }
    return render(request, 'task.html', context)



@is_auth
@change_task_perm
def change_status_task(request):
    task = get_task(id=request.POST['task_id'])
    task_status = StatusTaskForm(request.POST, instance=task['task'])
    if task_status.is_valid():
        task_status.save()
        change_status_signal.send(sender=task['task'])
        return redirect('/management/task/{}'.format(request.POST['task_id']))


@is_auth
@change_task_perm
def change_responsible_task(request):
    task = get_task(id=request.POST['task_id'])
    task_responsibles = ResponsibleTaskForm(request.POST, instance=task['task'])
    if task_responsibles.is_valid():
        task_responsibles.save()
        change_responsible_signal.send(sender=task['task'])
        return redirect('/management/task/{}'.format(request.POST['task_id']))


@is_auth
def user_info(request, id):
    data = user_inform(id=id)
    context ={
        'data': data,
    }
    return render(request, 'userinfo.html', context)


@is_auth
def my_project(request, id):
    data = project_information(id=id)
    sprint_create_form = CreateSprintForm()
    issue_create_form = CreateIssueForm()
    context = {
        'data': data,
        'sprint_create_form': sprint_create_form,
        'issue_create_form': issue_create_form,
    }
    return render(request, 'project.html', context)


@is_auth
def sprint(request, id):
    comentservis = ComentServis(request, id)
    sprint = get_sprint(id=id)
    userstorys = get_list_userstorys(id=id)
    coments = comentservis.get_coment_for_sprint()
    sprint_status = StatusSprintForm(request.POST, instance=sprint['sprint'])
    responsible_sprint = ChangeResponsibleForm(request.POST, instance=sprint['sprint'])
    form_add_coment = CreateComentForm()
    form_add_userstory = CreateUserStoryForm()
    context = {
        'sprint': sprint,
        'sprint_status': sprint_status,
        'responsible_sprint': responsible_sprint,
        'userstorys': userstorys,
        'coments': coments,
        'form_add_coment': form_add_coment,
        'form_add_userstory': form_add_userstory,
    }
    return render(request, 'sprint.html', context)


@is_auth
@change_sprit_perm
def change_status_sprint(request):
    sprint = get_sprint(id=request.POST['sprint_id'])
    sprint_status = StatusSprintForm(request.POST, instance=sprint['sprint'])
    if sprint_status.is_valid():
        sprint_status.save()
        change_status_signal.send(sender=sprint['sprint'])
        return redirect('/management/sprint/{}'.format(request.POST['sprint_id']))


@is_auth
@change_sprit_perm
def change_responsible_sprint(request):
    sprint = get_sprint(id=request.POST['sprint_id'])
    sprint_status = ChangeResponsibleForm(request.POST, instance=sprint['sprint'])
    if sprint_status.is_valid():
        sprint_status.save()
        change_responsible_signal.send(sender=sprint['sprint'])
        return redirect('/management/sprint/{}'.format(request.POST['sprint_id']))


@is_auth
@add_sprint_perm
def create_sprint(request):
    data = add_sprint(request.user, request.POST)
    context = {
        'data': data,
    }
    if data:
        return render(request, 'SuccessfullyCreatedSprint.html')


@is_auth
@add_issue_perm
def create_issue(request):
    data = add_issue(request.user, request.POST)
    return render(request, 'SuccessfullyCreatedIssue.html')


@is_auth
def list_issues(request, id):
    data = issues_for_project(id)
    context = {
        'data': data,
    }
    return render(request, 'listissues.html', context)


@is_auth
def list_issues_two(request, id):
    data = two_list_issues(request, id)
    context = {
        'data': data,
    }
    return render(request, 'AlternativeTemplate.html', context)


@is_auth
@chenge_issue_perm
def change_status_issue_two(request):
    issue = get_issue(request, request.POST['issue_id'])
    issue_status = StatusIssueForm(request.POST, instance=issue['issue'])
    if issue_status.is_valid():
        issue_status.save()
    return redirect('/management/list-issues-two/{}'.format(request.POST['project_id']))


@is_auth
def issue_info(request, id):
    data = get_issue(request, id)
    comentservis = ComentServis(request, data['issue'].id)
    coments = comentservis.get_coments_for_issue()
    context = {
        'data': data,
        'coments': coments,
    }
    return render(request, 'IssueInfo.html', context)

@is_auth
@chenge_issue_perm
def change_status_issue(request):

CRM/management/templates/AddIssue.html
ФОРМА ДОБАВЛЕНИЯ ЗАПРОСА<br>
<form action="/management/create-issue/"  method="post">
{% csrf_token %}
{{ issue_create_form.as_p }}
<input type="hidden" name="project_id" value={{ project_id }}>
<input value="Отправить запрос" type="submit">
</form>

CRM/management/templates/AddSprint.html
ФОРМА ДОБАВЛЕНИ СПРИНТА<br>
<form action="/management/create-sprint/"  method="post">
{% csrf_token %}
{{ sprint_create_form.as_p }}
<input type="hidden" name="project_id" value={{ project_id }}>
<input value="Создать спринт" type="submit">
</form>

CRM/management/templates/AlternativeTemplate.html
{% for i in data.data %}
Запросы для проекта <a href="/management/my-project/{{ i.0.project.id }}">{{ i.0.project.name }}</a><br>
Запрос создал <a href="/management/user/{{ i.0.created_by.id }}"> {{ i.0.created_by }} </a><br>
Ответственный <a href="/management/user/{{ i.0.responsible.id }}"> {{ i.0.responsible }} </a><br>
<form action="/management/change-status-issue-two/" method="post">
{% csrf_token %}
Статус запроса: {{ i.0.status }}<br>
{{ i.1.as_p }}<br>
<input type="hidden" name="issue_id" value={{ i.0.id }}>
<input type="hidden" name="project_id" value={{ i.0.project.id }}>
<input value="Обновить статус" type="submit">
</form>
Текст: {{ i.0.body }}<br>
Дата создания: {{ i.0.date_create }}<br>
Дадта обновления: {{ i.0.date_update }}<br>
Дата закрытия: {{ i.0.date_closed }}<br>
<hr>
{% endfor %}

CRM/management/templates/FoundObjects.html
По Вашему запросу найдено:<br>
Спринты<br>
{% for x in data.sprint %}
<a href="/management/sprint/{{ x.id }}"> {{ x.name }} </a> номер {{ x.number }}<br>
{% endfor %}
<hr>
Пользовательские истории:<br>
{% for x in data.userstory %}
<a href="/management/userstory/{{ x.id }}"> {{ x.name }} </a> номер {{ x.number }}<br>
{% endfor %}
<hr>
Задачи:<br>
{% for x in  data.task %}
<a href="/management/task/{{ x.id }}"> {{ x.name }} </a> номер {{ x.number }} <br>
{% endfor %}
<hr>
Запросы:<br>
{% for x in data.issue %}
<a href="/management/issue-info/{{ x.id }}"> {{ x.name }} </a> номер {{ x.number }} <br>
{% endfor %}

CRM/management/templates/NotPermChengeTask.html
У Вас не полномочий на изминения одержания задачи<br>
<a href="/management/homepage"> Главная страница </a><br>

CRM/management/templates/SuccessfullyCreatedSprint.html
Спринт успешно создан <br>
<a href="/management/homepage"> Главная страница </a><br>

CRM/management/templates/chekin.html
<form action="/management/register" method="post">
{% csrf_token %}
{{ chekin.as_p }}
<input type="hidden" name="project_id" value={{ project_id }}>
<input value="Зарегестрировать" type="submit">
</form>
Вернутся на страницу <a href="/management/login"> входа </a><br>

CRM/management/templates/homepage.html
{% if user.is_authenticated %}
Главная страница<br>
<a href="/management/invite"> Отправить приглашение </a><br>
Мои проекты:<br>
{% for x in my_projects %}
<a href="/management/my-project/{{x.id}}"> {{ x.name }} </a><br>
{%endfor%}
<hr>
ФОРМА СОЗДАНИЯ ПРОЕКТА<br>
<form action="/management/create-project/"  method="post">
{% csrf_token %}
{{ form_add_project.as_p }}
<input type="hidden" name="user_id" value={{ user.id }}>
<input value="Создать проект " type="submit">
</form>
<hr>
<a href="/management/logout"> Выход </a><br>
{% else %}
<a href="/login"> Авторизации </a><br>
<a href="/chekin"> Регистрация </a>
{% endif %}

CRM/management/templates/listissues.html
Запросы для проекта <a href="/management/my-project/{{ data.project.id }}">{{ data.project.name }}</a><br>
Название запроса:<br>
{% for x in data.issues %}
<a href="/management/issue-info/{{ x.id }}"> {{ x.name }} </a><br>
{% endfor %}

CRM/management/templates/notregister.html
Вы не зарегестрированы.

CRM/management/templates/sentnotification.html
Ви успешно прошли регистрацию <br>
Вернутся на страницу <a href="/management/login"> входа </a><br>

CRM/management/templates/userinfo.html
Ник пользователя: {{ data.user.username }}<br>
Имя пользователя: {{ data.user.first_name }}<br>
Фамилия пользователя: {{ data.user.last_name }}<br>
Електронный ящик пользователя: {{ data.user.email }}<br>


CRM/management/templates/userisnotfound.html
Пользователь не найден.

CRM/management/templates/userstory.html
Имя пользовательской истории: {{ userstory.userstory.name }}<br>
Пользовательскую историю создал: <a href="/management/user/{{ data.userstory.created_by.id }}"> {{ userstory.userstory.created_by }} </a><br>
Ответственные за пользовательскую историю: <br>
{% for x in  userstory.userstory.responsibles.all %}
<a href="/management/user/{{ x.id }}"> {{ x.username }} </a><br>
{% endfor %}
Назначить нового(..ых) ответственного(..ых)<br>
{% if perms.tasker.change_userstory %}
<form action="/management/change-responsible-userstory/"  method="post">
{% csrf_token %}
{{ form_responsible_form.as_p }}
<input type="hidden" name="userstory_id" value={{ userstory.userstory.id }}>
<input value="Обновить" type="submit">
</form>
{% endif %}
Статус пользовательской истории {{ userstory.userstory.status }}<br>
{% if perms.tasker.change_userstory %}
<form action="/management/change-status-userstory/"  method="post">
{% csrf_token %}
{{ form_starus_userstoty.as_p }}
<input type="hidden" name="userstory_id" value={{ userstory.userstory.id }}>
<input value="Обновить статус" type="submit">
</form>
{% endif %}
Описание пользовательской истории: {{ userstory.userstory.description }}<br>
Дата создания: {{ userstory.userstory.date_create }}<br>
Дата обновления: {{ userstory.userstory.data_update }}<br>
Дата закрытия: {{ userstory.userstory.data_closed }}<br>
ЗАДАЧИ<br>
{% for x in  tasks.tasks %}
<a href="/management/task/{{ x.id }}"> {{ x.name }} </a><br>
{% endfor %}
<hr>
<a href="/management/sprint/{{ userstory.userstory.sprint.id }}"> Вернутся на спринт </a><br>
<hr>
ФОРМА ДОБАВЛЕНИЯ ЗАДАЧИ
{% if perms.tasker.add_task %}
<form action="/management/create-task-for-userstory/"  method="post">
{% csrf_token %}
{{ form_add_task.as_p }}
<input type="hidden" name="userstory_id" value={{ userstory.userstory.id }}>
<input value="Добавить задачу " type="submit">
</form>
{% endif %}
<hr>
КОМЕНТАРИИ:<br>
{% for i in coments.coments %}
Коментарий добавил:<a href="/management/user/{{ i.created_by.id }}"> {{ i.created_by }}</a><br>
Текс: {{i.body }}<br>
Дата создания {{ i.date_create }}<br>
{% endfor %}
<hr>
ФОРМА ДОБАВЛЕНИЯ КОМЕНТАРИЯ
{% if perms.tasker.can_add_coment_for_userstory %}
<form action="/management/create-coment-for-userstory/"  method="post">
{% csrf_token %}
{{ form_add_coment.as_p }}
<input type="hidden" name="userstory_id" value={{ userstory.userstory.id }}>
<input value="Добавить коментарий" type="submit">
</form>
{% endif %}